### ISSUE TITLE
Probably some files are missing

### ISSUE THREAD

**Issue by shujaatak** [theilem/uavEE#2]
These are the files which are missing:
```
"radio_comm/select_mission.h"
"radio_comm/select_maneuver.h"
"radio_comm/request_data.h"
"radio_comm/tune_generic.h"
"radio_comm/tune_pid.h"
"radio_comm/serialized_service.h"
"radio_comm/send_advanced_control.h"
```

**Comment by MacProSector** [comment]
Please try compiling the project using catkin_make multiple time despite the errors stated above. It is due to the fact that the ROS msg files were sometimes generated after the files were used.

**Comment by shujaatak** [comment]
Indeed running catkin_make multiple time solved this issue.
